const Customersdata = [
  {
    id: 1,
    orderId: 257,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "Pending",
  },
  {
    id: 2,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "In Process",
  },
  {
    id: 3,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "In Process",
  },
  {
    id: 4,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "Pending",
  },
  {
    id: 5,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "Pending",
  },
  {
    id: 6,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "In Process",
  },
  {
    id: 7,
    orderId: 157,
    name: "Classic Cheese Burger",
    cost: 300,
    quantity: 4,
    deliveryDate: "15-03-2021",
    address: "abc",
    status: "Pending",
  },
];

export default Customersdata;
